### ISSUE TITLE
"Call to a member function getMarshaler() on null"

### ISSUE THREAD

**Issue by acgfbr** [baopham/laravel-dynamodb#221]
I`m running laravel in aws lambda with this package, but on update any model the exception: "Call to a member function getMarshaler() on null" is throwed.

```php
0091ea71-56ce-49cc-a4c4-745d1c4a0f5e	Invoke Error	
{
    "errorType": "Error",
    "errorMessage": "Call to a member function getMarshaler() on null",
    "stack": [
        "#0 /var/task/vendor/baopham/dynamodb/src/DynamoDbModel.php(78): BaoPham\\DynamoDb\\DynamoDbModel->setupDynamoDb()",
        "#1 /var/task/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1706): BaoPham\\DynamoDb\\DynamoDbModel->__construct()",
        "#2 /var/task/app/helpers.php(9): Illuminate\\Database\\Eloquent\\Model::__callStatic('where', Array)",
        "#3 /var/task/app/Console/Actions/Products/Stock/SkyhubAction.php(21): decrementCurrent('5166')",
        "#4 /var/task/app/Console/Routers/Products/StockRouter.php(21): App\\Console\\Actions\\Products\\Stock\\SkyhubAction->execute()",
        "#5 /var/task/app/Console/Routers/SnsTypeRouter.php(21): App\\Console\\Routers\\Products\\StockRouter->execute()",
        "#6 /var/task/public/sns.php(20): App\\Console\\Routers\\SnsTypeRouter->execute()",
        "#7 /var/task/public/sns.php(41): SnsLimiterHandler->handleSns(Object(Bref\\Event\\Sns\\SnsEvent), Object(Bref\\Context\\Context))",
        "#8 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(107): {closure}(Array, Object(Bref\\Context\\Context))",
        "#9 /var/task/vendor/bref/bref/src/functions.php(19): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
        "#10 /var/task/public/sns.php(42): lambda(Object(Closure))",
        "#11 {main}"
    ]
}
```

**Version info**

* Laravel: 7.0
* laravel-dynamodb: latest

**Comment by thomasedwards** [comment]
> I`m running laravel in aws lambda

Wow!

Can you tell us more about how the item is formatted? Can you show us an example of the item? Can you show us the Eloquent syntax you’re using to make the query?

**Comment by acgfbr** [comment]
sorry, it was my mistake, I created a specific handler for sns and he was not autoloading the lib properly, I will close the issue.

**Comment by thomasedwards** [comment]
Ah no worries!
